version: '2.1'
services:
  mariadb:
    image: mariadb:10.5
    restart: always
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
    healthcheck:
      test: out=$$(mysqladmin ping -h localhost -P 3306 -u root --password=$${MYSQL_ROOT_PASSWORD} 2>&1); echo $$out | grep 'mysqld is alive' || { echo $$out; exit 1; }
  node:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_ENV: development
    depends_on:
      mariadb:
        condition: service_healthy
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
      - MYSQL_HOST=mariadb
    ports:
      - "${NODE_PORT}:3000"
    volumes:
      - ./:/app/
      - /app/node_modules/
    working_dir: /app
    command: [ "npm", "run", "start" ]
